services:
  {{PROJECT_NAME}}:
    build: ./php
    image: {{PROJECT_NAME}}_php:latest
    container_name: {{PROJECT_NAME}}
    hostname: "{{PROJECT_NAME}}"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on:
      - {{PROJECT_NAME}}_db

  {{PROJECT_NAME}}_db:
    image: mariadb:10.11
    container_name: {{PROJECT_NAME}}_db
    restart: unless-stoppedservices:
  php:
    build:
      context: ./php
    container_name: ksi_php
    volumes:
      - ./src:/var/www/html
    environment:
      - PROJECT_NAME=ksi
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: ksi_nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - php

  db:
    image: mariadb:10.11
    container_name: ksi_db
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: ksi
      MYSQL_ROOT_PASSWORD: p455w0rd
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: lex69
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: test
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: {{PROJECT_NAME}}_db

  {{PROJECT_NAME}}_nginx:
    build: ./nginx
    image: {{PROJECT_NAME}}_nginx:latest
    container_name: {{PROJECT_NAME}}_nginx
    hostname: "{{PROJECT_NAME}}_nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - {{PROJECT_NAME}}
